### ISSUE TITLE
l2_reg remained unchanged during the training process.

### ISSUE THREAD

**Issue by MeteorBless** [ljb121002/fednar#1]
Thank you for your dedication and thoughtfully designed experiments. Due to my limited capabilities, I conducted the experiments using the default settings (with the 'use_nar' parameter). However, I observed that l2_reg remained constant throughout the training process. Could you please provide clarification on the potential issue? Is l2_reg intended to contribute to adaptive weight decay in the code?

**Comment by ljb121002** [comment]
Thanks for using our codes. Please check [this line](https://github.com/ljb121002/fednar/blob/master/util_general.py#L63), where the gradient of `net.parameters()` included weight decay. So the clipping applied here is to both the original gradient and the weight decay, which means the actual weight decay is adaptive, aligning with the description provided in our paper.
